### ISSUE TITLE
Unsupported 16-bit Application (Win10)

### ISSUE THREAD

**Issue by mdiBox** [SuiMachine/Condemned-DDS-Converter#1]
Hello!

How can I use this utility?
An error occurs on Win 10: "Unsupported 16-bit Application"

Script for *.bat:
for /r %%v in (*.dds) do (Condemned-DDS-converter.exe  %%v)

**Comment by SuiMachine** [comment]
That seems like something that could happen if you try to save a web page instead of file itself. 

Go to:
https://github.com/SuiMachine/Condemned-DDS-Converter/blob/master/Release/Condemned-DDS-converter.exe
and click Download in there - that should start downloading the file.

**Comment by mdiBox** [comment]
Thanks!!!
