### ISSUE TITLE
mass converting files question

### ISSUE THREAD

**Issue by ctrlalt-666** [SuiMachine/Condemned-DDS-Converter#2]
Hey Suimachine, how do I use the script for mass converting exactly? I can't code.

**Comment by SuiMachine** [comment]
Make sure your system doesn't hide known extensions in file names.
Create a new empty text file, paste the content mentioned in readme, change the extension from txt to cmd and run it (make sure the exe is inside the folder with cmd). If there is some problems, you can also press Win+R and type in cmd, then use command-line console to navigate to the folder with the cmd file you created and then launch it, so you get to see what went wrong.

**Comment by ctrlalt-666** [comment]
Thank you!
